### PR TITLE
Fix #92

### LINKED ISSUE #92: Duplication Bug!
Hi, 

   Just got a really nasty and easy to reproduce dup bug. If you have 2 Hungry bag in your inventory and you recover any loose item. Each hungry bag will contain the recovered item effectively duplicating it. Those item stay after a delog/relog so they are not client ghost.

Thank you

### PR DESCRIPTION
**Pull request by kimfy**

### CODE REVIEW

**Comment by kimfy** [comment]
Hey @BluSunrize will this PR be considered, at all?

**Comment by BluSunrize** [comment]
Given the fact that 1.7 is pretty dead to me and I haven't worked on WG in months? For now probably not.

**Comment by kimfy** [comment]
That's understandable! :+1:

**Comment by chaos234** [comment]
But why not merging it? Each dev can then compile it self even if you don't work on it any more (which is bad I think)

**Comment by kimfy** [comment]
I'd be happy to keep Witching Gadgets alive for 1.7.10 in my own fork - if @BluSunrize is ok with that. No new features, only bug fixes. I still play 1.7.10 and don't really have an urge to move to 1.10.x

**Comment by ghost** [comment]
It might be dead to you but some people still use it. I used to dislike this mod but now I play it in most of my builds. And believe it or not there's a lot of dedicated 1.7.10 Minecrafteers still playing it and even making mods for this version. Not everyone cares to always updated to the latest version and not everyone likes the new versions anyway.

**Pull request closed without merging**
